// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ESP32S3_LVGL_FOC

#ifndef _ESP32S3_LVGL_FOC_UI_H
#define _ESP32S3_LVGL_FOC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Header_Date;
extern lv_obj_t * ui_Header_Time;
extern lv_obj_t * ui_Arc_Group;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Temp_Bg;
extern lv_obj_t * ui_Temp_Num_Bg;
extern lv_obj_t * ui_Label_Celsius;
void ui_event_angle_Control(lv_event_t * e);
void ui_event_bright_Control(lv_event_t * e);
extern lv_obj_t * ui_angle_Control;
extern lv_obj_t * ui_bright_Control;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * ui_TextArea1;

LV_IMG_DECLARE(ui_img_btn_print_down_png);    // assets\btn_print_down.png


LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small_Font);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
