// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ESP32S3_LVGL_FOC

#ifndef _ESP32S3_LVGL_FOC_UI_COMP_HOOK_H
#define _ESP32S3_LVGL_FOC_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Header_Time_create_hook(lv_obj_t * comp);
void ui_comp_Header_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
