// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ESP32S3_LVGL_FOC

#ifndef _ESP32S3_LVGL_FOC_UI_COMP_H
#define _ESP32S3_LVGL_FOC_UI_COMP_H

#ifdef __cplusplus
extern "C" {
#endif


lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT Header Time
#define UI_COMP_HEADER_TIME_HEADER_TIME 0
#define _UI_COMP_HEADER_TIME_NUM 1
lv_obj_t * ui_Header_Time_create(lv_obj_t * comp_parent);

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_HEADER_DATE 1
#define UI_COMP_HEADER_HEADER_TIME 2
#define _UI_COMP_HEADER_NUM 3
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
