// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ESP32S3_LVGL_FOC


#include "ui.h"
#include "ui_helpers.h"
#include "ui_comp.h"

uint32_t LV_EVENT_GET_COMP_CHILD;

typedef struct {
    uint32_t child_idx;
    lv_obj_t * child;
} ui_comp_get_child_t;

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx)
{
    ui_comp_get_child_t info;
    info.child = NULL;
    info.child_idx = child_idx;
    lv_event_send(comp, LV_EVENT_GET_COMP_CHILD, &info);
    return info.child;
}

void get_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = lv_event_get_user_data(e);
    ui_comp_get_child_t * info = lv_event_get_param(e);
    info->child = c[info->child_idx];
}

void del_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = lv_event_get_user_data(e);
    lv_mem_free(c);
}


// COMPONENT Header Time

lv_obj_t * ui_Header_Time_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Header_Time;
    cui_Header_Time = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Header_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Header_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Header_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Header_Time, "AM 7:45");
    lv_obj_set_style_text_color(cui_Header_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Header_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_TIME_NUM);
    children[UI_COMP_HEADER_TIME_HEADER_TIME] = cui_Header_Time;
    lv_obj_add_event_cb(cui_Header_Time, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Header_Time, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Header_Time_create_hook(cui_Header_Time);
    return cui_Header_Time;
}



// COMPONENT Header

lv_obj_t * ui_Header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Header;
    cui_Header = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_Header, 50);
    lv_obj_set_width(cui_Header, lv_pct(100));
    lv_obj_set_align(cui_Header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(cui_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Header, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Header_Date;
    cui_Header_Date = lv_label_create(cui_Header);
    lv_obj_set_width(cui_Header_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Header_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Header_Date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Header_Date, "Friday, March 11, 2022");
    lv_obj_set_style_text_color(cui_Header_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Header_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Header_Time;
    cui_Header_Time = lv_label_create(cui_Header);
    lv_obj_set_width(cui_Header_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Header_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Header_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Header_Time, "AM 7:45");
    lv_obj_set_style_text_color(cui_Header_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Header_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
    children[UI_COMP_HEADER_HEADER] = cui_Header;
    children[UI_COMP_HEADER_HEADER_DATE] = cui_Header_Date;
    children[UI_COMP_HEADER_HEADER_TIME] = cui_Header_Time;
    lv_obj_add_event_cb(cui_Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Header_create_hook(cui_Header);
    return cui_Header;
}

