// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ESP32S3_LVGL_FOC

#include "ui.h"

void fan_speed_value(lv_event_t * e)
{
	// Your code here
}
